import Foundation

struct IconOption {
    let symbolName: String
    let keywords: [String]
}

/// Curated SF Symbols for expense categories, with search keywords.
enum CategoryIcons {
    static let all: [IconOption] = [
        // Food & drink
        IconOption(symbolName: "fork.knife", keywords: ["food", "meal", "restaurant", "dining"]),
        IconOption(symbolName: "fork.knife.circle.fill", keywords: ["food", "meal", "lunch", "dinner"]),
        IconOption(symbolName: "cup.and.saucer.fill", keywords: ["coffee", "tea", "cafe", "chai"]),
        IconOption(symbolName: "mug.fill", keywords: ["coffee", "tea", "drink", "mug"]),
        IconOption(symbolName: "takeoutbag.and.cup.and.straw.fill", keywords: ["takeout", "fast food", "delivery", "snack"]),
        IconOption(symbolName: "wineglass.fill", keywords: ["wine", "drinks", "alcohol", "bar"]),
        IconOption(symbolName: "birthday.cake.fill", keywords: ["cake", "birthday", "dessert", "celebration"]),
        IconOption(symbolName: "carrot.fill", keywords: ["vegetables", "groceries", "healthy", "produce"]),
        IconOption(symbolName: "fish.fill", keywords: ["fish", "seafood", "meat"]),
        IconOption(symbolName: "popcorn.fill", keywords: ["snacks", "movie", "popcorn"]),
        IconOption(symbolName: "frying.pan.fill", keywords: ["cooking", "kitchen", "pan"]),
        IconOption(symbolName: "refrigerator.fill", keywords: ["fridge", "kitchen", "appliance", "groceries"]),
        IconOption(symbolName: "basket.fill", keywords: ["groceries", "basket", "shopping", "market"]),
        IconOption(symbolName: "waterbottle.fill", keywords: ["water", "drink", "bottle"]),

        // Shopping
        IconOption(symbolName: "bag.fill", keywords: ["shopping", "purchase", "bag", "mall"]),
        IconOption(symbolName: "cart.fill", keywords: ["shopping", "groceries", "cart", "supermarket"]),
        IconOption(symbolName: "handbag.fill", keywords: ["handbag", "purse", "fashion", "accessories"]),
        IconOption(symbolName: "tshirt.fill", keywords: ["clothes", "dress", "fashion", "apparel"]),
        IconOption(symbolName: "shoe.fill", keywords: ["shoes", "footwear", "sneakers"]),
        IconOption(symbolName: "hanger", keywords: ["clothes", "wardrobe", "laundry", "fashion"]),
        IconOption(symbolName: "tag.fill", keywords: ["price", "sale", "discount", "label"]),
        IconOption(symbolName: "shippingbox.fill", keywords: ["delivery", "package", "amazon", "parcel"]),
        IconOption(symbolName: "storefront.fill", keywords: ["shop", "store", "market", "local"]),
        IconOption(symbolName: "percent", keywords: ["discount", "sale", "offer", "interest"]),

        // Transport
        IconOption(symbolName: "car.fill", keywords: ["car", "vehicle", "drive", "taxi"]),
        IconOption(symbolName: "car.2.fill", keywords: ["cars", "vehicles", "carpool"]),
        IconOption(symbolName: "bolt.car.fill", keywords: ["electric car", "ev", "charging"]),
        IconOption(symbolName: "fuelpump.fill", keywords: ["fuel", "petrol", "gas", "diesel"]),
        IconOption(symbolName: "bus.fill", keywords: ["bus", "transit", "public transport", "commute"]),
        IconOption(symbolName: "tram.fill", keywords: ["tram", "metro", "train", "commute"]),
        IconOption(symbolName: "airplane", keywords: ["flight", "travel", "airline", "trip"]),
        IconOption(symbolName: "airplane.departure", keywords: ["flight", "departure", "travel", "vacation"]),
        IconOption(symbolName: "bicycle", keywords: ["bike", "cycling", "bicycle"]),
        IconOption(symbolName: "scooter", keywords: ["scooter", "bike", "two wheeler"]),
        IconOption(symbolName: "ferry.fill", keywords: ["ferry", "boat", "ship"]),
        IconOption(symbolName: "sailboat.fill", keywords: ["boat", "sailing", "cruise"]),
        IconOption(symbolName: "steeringwheel", keywords: ["driving", "car", "vehicle"]),
        IconOption(symbolName: "parkingsign", keywords: ["parking", "car", "toll"]),
        IconOption(symbolName: "road.lanes", keywords: ["road", "toll", "highway"]),

        // Home & utilities
        IconOption(symbolName: "house.fill", keywords: ["home", "rent", "house", "mortgage"]),
        IconOption(symbolName: "building.2.fill", keywords: ["apartment", "building", "society", "maintenance"]),
        IconOption(symbolName: "lightbulb.fill", keywords: ["electricity", "light", "idea", "power"]),
        IconOption(symbolName: "bolt.fill", keywords: ["electricity", "power", "energy", "utility"]),
        IconOption(symbolName: "wifi", keywords: ["internet", "broadband", "wifi", "network"]),
        IconOption(symbolName: "drop.fill", keywords: ["water", "utility", "bill"]),
        IconOption(symbolName: "flame.fill", keywords: ["gas", "cooking gas", "heating", "lpg"]),
        IconOption(symbolName: "wrench.and.screwdriver.fill", keywords: ["repair", "maintenance", "tools", "service"]),
        IconOption(symbolName: "hammer.fill", keywords: ["repair", "construction", "renovation", "diy"]),
        IconOption(symbolName: "paintbrush.fill", keywords: ["painting", "decor", "renovation", "art"]),
        IconOption(symbolName: "sofa.fill", keywords: ["furniture", "sofa", "home", "living room"]),
        IconOption(symbolName: "bed.double.fill", keywords: ["bed", "furniture", "hotel", "bedroom"]),
        IconOption(symbolName: "washer.fill", keywords: ["laundry", "washing machine", "appliance"]),
        IconOption(symbolName: "key.fill", keywords: ["key", "rent", "deposit", "lock"]),
        IconOption(symbolName: "lock.fill", keywords: ["security", "lock", "safe"]),
        IconOption(symbolName: "trash.fill", keywords: ["waste", "garbage", "disposal"]),
        IconOption(symbolName: "spigot.fill", keywords: ["plumbing", "water", "tap"]),
        IconOption(symbolName: "air.conditioner.horizontal.fill", keywords: ["ac", "air conditioner", "cooling", "appliance"]),

        // Health & fitness
        IconOption(symbolName: "cross.case.fill", keywords: ["medical", "doctor", "hospital", "health"]),
        IconOption(symbolName: "pills.fill", keywords: ["medicine", "pharmacy", "pills", "drugs"]),
        IconOption(symbolName: "heart.fill", keywords: ["health", "love", "heart"]),
        IconOption(symbolName: "heart.text.square.fill", keywords: ["health record", "medical", "checkup"]),
        IconOption(symbolName: "stethoscope", keywords: ["doctor", "medical", "checkup", "clinic"]),
        IconOption(symbolName: "syringe.fill", keywords: ["vaccine", "injection", "medical"]),
        IconOption(symbolName: "bandage.fill", keywords: ["injury", "first aid", "medical"]),
        IconOption(symbolName: "figure.run", keywords: ["running", "exercise", "fitness", "sports"]),
        IconOption(symbolName: "figure.walk", keywords: ["walking", "exercise", "fitness"]),
        IconOption(symbolName: "dumbbell.fill", keywords: ["gym", "workout", "fitness", "weights"]),
        IconOption(symbolName: "tennis.racket", keywords: ["tennis", "sports", "game"]),
        IconOption(symbolName: "eye.fill", keywords: ["eye", "optician", "vision", "glasses"]),
        IconOption(symbolName: "brain.head.profile", keywords: ["mental health", "therapy", "mind"]),

        // Finance
        IconOption(symbolName: "creditcard.fill", keywords: ["credit card", "card", "payment", "bill"]),
        IconOption(symbolName: "banknote.fill", keywords: ["cash", "money", "notes", "currency"]),
        IconOption(symbolName: "dollarsign.circle.fill", keywords: ["money", "dollar", "currency", "payment"]),
        IconOption(symbolName: "indianrupeesign.circle.fill", keywords: ["rupee", "money", "currency", "inr"]),
        IconOption(symbolName: "chart.line.uptrend.xyaxis", keywords: ["investment", "stocks", "growth", "market"]),
        IconOption(symbolName: "chart.pie.fill", keywords: ["budget", "allocation", "chart", "portfolio"]),
        IconOption(symbolName: "chart.bar.fill", keywords: ["stats", "chart", "report"]),
        IconOption(symbolName: "building.columns.fill", keywords: ["bank", "loan", "institution", "government"]),
        IconOption(symbolName: "arrow.left.arrow.right", keywords: ["transfer", "exchange", "swap", "self transfer"]),
        IconOption(symbolName: "wallet.pass.fill", keywords: ["wallet", "pass", "money"]),
        IconOption(symbolName: "lock.shield.fill", keywords: ["insurance", "protection", "security"]),
        IconOption(symbolName: "signature", keywords: ["contract", "document", "signing", "agreement"]),
        IconOption(symbolName: "doc.text.fill", keywords: ["document", "bill", "invoice", "tax"]),
        IconOption(symbolName: "briefcase.fill", keywords: ["work", "business", "job", "office"]),
        IconOption(symbolName: "hourglass", keywords: ["pending", "time", "deposit", "maturity"]),

        // Entertainment & leisure
        IconOption(symbolName: "film.fill", keywords: ["movie", "cinema", "film"]),
        IconOption(symbolName: "tv.fill", keywords: ["tv", "television", "streaming", "ott"]),
        IconOption(symbolName: "gamecontroller.fill", keywords: ["gaming", "games", "console"]),
        IconOption(symbolName: "music.note", keywords: ["music", "spotify", "songs", "concert"]),
        IconOption(symbolName: "headphones", keywords: ["music", "audio", "podcast", "headphones"]),
        IconOption(symbolName: "ticket.fill", keywords: ["tickets", "event", "show", "movie"]),
        IconOption(symbolName: "theatermasks.fill", keywords: ["theatre", "drama", "arts", "show"]),
        IconOption(symbolName: "camera.fill", keywords: ["camera", "photography", "photos"]),
        IconOption(symbolName: "photo.fill", keywords: ["photos", "pictures", "prints"]),
        IconOption(symbolName: "party.popper.fill", keywords: ["party", "celebration", "festival", "event"]),
        IconOption(symbolName: "beach.umbrella.fill", keywords: ["beach", "vacation", "holiday", "leisure"]),
        IconOption(symbolName: "tent.fill", keywords: ["camping", "outdoors", "trek"]),
        IconOption(symbolName: "binoculars.fill", keywords: ["sightseeing", "tour", "explore"]),
        IconOption(symbolName: "sparkles", keywords: ["special", "treat", "magic", "fun"]),

        // Family & people
        IconOption(symbolName: "person.fill", keywords: ["person", "individual", "personal"]),
        IconOption(symbolName: "person.2.fill", keywords: ["people", "friends", "couple", "lending"]),
        IconOption(symbolName: "person.3.fill", keywords: ["group", "team", "community"]),
        IconOption(symbolName: "figure.and.child.holdinghands", keywords: ["family", "child", "kids", "parenting"]),
        IconOption(symbolName: "figure.2.and.child.holdinghands", keywords: ["family", "parents", "children"]),
        IconOption(symbolName: "pawprint.fill", keywords: ["pet", "dog", "cat", "vet"]),
        IconOption(symbolName: "teddybear.fill", keywords: ["baby", "kids", "toys", "child"]),
        IconOption(symbolName: "stroller.fill", keywords: ["baby", "stroller", "infant"]),
        IconOption(symbolName: "gift.fill", keywords: ["gift", "present", "donation", "birthday"]),
        IconOption(symbolName: "heart.circle.fill", keywords: ["charity", "donation", "care", "love"]),
        IconOption(symbolName: "hands.clap.fill", keywords: ["support", "tip", "appreciation"]),

        // Education & work
        IconOption(symbolName: "graduationcap.fill", keywords: ["education", "school", "college", "tuition"]),
        IconOption(symbolName: "book.fill", keywords: ["books", "reading", "study"]),
        IconOption(symbolName: "books.vertical.fill", keywords: ["library", "books", "study"]),
        IconOption(symbolName: "backpack.fill", keywords: ["school", "backpack", "supplies"]),
        IconOption(symbolName: "pencil", keywords: ["stationery", "writing", "supplies"]),
        IconOption(symbolName: "ruler.fill", keywords: ["stationery", "measure", "school"]),
        IconOption(symbolName: "desktopcomputer", keywords: ["computer", "pc", "work", "electronics"]),
        IconOption(symbolName: "laptopcomputer", keywords: ["laptop", "computer", "work", "electronics"]),
        IconOption(symbolName: "printer.fill", keywords: ["printing", "printer", "office"]),

        // Tech & communication
        IconOption(symbolName: "phone.fill", keywords: ["phone", "call", "mobile", "recharge"]),
        IconOption(symbolName: "iphone", keywords: ["mobile", "smartphone", "gadget", "device"]),
        IconOption(symbolName: "envelope.fill", keywords: ["mail", "post", "letter"]),
        IconOption(symbolName: "paperplane.fill", keywords: ["send", "message", "transfer"]),
        IconOption(symbolName: "antenna.radiowaves.left.and.right", keywords: ["mobile plan", "network", "signal", "recharge"]),
        IconOption(symbolName: "globe", keywords: ["internet", "web", "international", "domain"]),
        IconOption(symbolName: "cloud.fill", keywords: ["cloud", "storage", "icloud", "backup"]),
        IconOption(symbolName: "externaldrive.fill", keywords: ["storage", "drive", "backup", "hardware"]),
        IconOption(symbolName: "keyboard", keywords: ["keyboard", "accessories", "computer"]),
        IconOption(symbolName: "headset", keywords: ["headset", "gaming", "audio", "support"]),

        // Personal care
        IconOption(symbolName: "scissors", keywords: ["haircut", "salon", "barber", "grooming"]),
        IconOption(symbolName: "comb.fill", keywords: ["grooming", "salon", "hair"]),
        IconOption(symbolName: "shower.fill", keywords: ["bath", "shower", "toiletries"]),
        IconOption(symbolName: "face.smiling", keywords: ["wellness", "happy", "self care"]),
        IconOption(symbolName: "crown.fill", keywords: ["luxury", "premium", "treat"]),
        IconOption(symbolName: "eyeglasses", keywords: ["glasses", "spectacles", "optician"]),

        // Travel
        IconOption(symbolName: "suitcase.fill", keywords: ["travel", "luggage", "trip", "vacation"]),
        IconOption(symbolName: "suitcase.rolling.fill", keywords: ["travel", "luggage", "airport"]),
        IconOption(symbolName: "globe.asia.australia.fill", keywords: ["world", "international", "travel"]),
        IconOption(symbolName: "mappin.and.ellipse", keywords: ["location", "place", "destination"]),
        IconOption(symbolName: "location.fill", keywords: ["location", "navigation", "gps"]),
        IconOption(symbolName: "map.fill", keywords: ["map", "trip", "navigation", "tour"]),

        // Misc
        IconOption(symbolName: "questionmark.circle.fill", keywords: ["uncategorized", "unknown", "other", "misc"]),
        IconOption(symbolName: "circle.fill", keywords: ["default", "dot", "generic"]),
        IconOption(symbolName: "star.fill", keywords: ["favorite", "star", "special"]),
        IconOption(symbolName: "bell.fill", keywords: ["reminder", "alert", "notification"]),
        IconOption(symbolName: "calendar", keywords: ["date", "schedule", "monthly", "planner"]),
        IconOption(symbolName: "clock.fill", keywords: ["time", "hourly", "schedule"]),
        IconOption(symbolName: "umbrella.fill", keywords: ["insurance", "rain", "protection"]),
        IconOption(symbolName: "snowflake", keywords: ["winter", "cooling", "cold"]),
        IconOption(symbolName: "sun.max.fill", keywords: ["summer", "sun", "solar"]),
        IconOption(symbolName: "moon.fill", keywords: ["night", "sleep", "moon"]),
        IconOption(symbolName: "leaf.fill", keywords: ["nature", "eco", "plants", "garden"]),
        IconOption(symbolName: "tree.fill", keywords: ["garden", "nature", "outdoors"]),
        IconOption(symbolName: "flag.fill", keywords: ["goal", "milestone", "flag"]),
        IconOption(symbolName: "battery.100percent.bolt", keywords: ["charging", "battery", "power"]),
        IconOption(symbolName: "puzzlepiece.fill", keywords: ["hobby", "puzzle", "games"]),
        IconOption(symbolName: "medal.fill", keywords: ["award", "achievement", "sports"]),
    ]
}
